{% set name = "flake8-eradicate" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-eradicate-{{ version }}.tar.gz
  sha256: acaa1b6839ff00d284b805c432fdfa6047262bd15a5504ec945797e87b4de1fa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - attrs
    - eradicate >=2.0,<3.0
    - flake8 >=3.5,<4.0
    - python >=3.6,<4.0

test:
  imports:
    - flake8_eradicate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sobolevn/flake8-eradicate
  summary: Flake8 plugin to find commented out code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
