{% set name = "flake8-eradicate" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-eradicate-{{ version }}.tar.gz
  sha256: 3088cfd6717d1c9c6c3ac45ef2e5f5b6c7267f7504d5a74b781500e95cb9c7e1

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - attrs
    - eradicate >=2.0
    - flake8 >=3.5,<6.0
    - python >=3.6,<4.0

test:
  imports:
    - flake8_eradicate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sobolevn/flake8-eradicate
  summary: Flake8 plugin to find commented out code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
